// S-57 object class readable names and the clickable-layer allowlist.
// Extracted from s57-popover.component.ts so consumers can keep using
// the lookup table after the popover component itself was retired.

export const S57_NAMES: Record<string, string> = {
  SOUNDG: 'Sounding',
  DEPCNT: 'Depth Contour',
  OBSTRN: 'Obstruction',
  UWTROC: 'Underwater Rock',
  WRECKS: 'Wreck',
  LIGHTS: 'Light',
  BOYLAT: 'Lateral Buoy',
  BOYCAR: 'Cardinal Buoy',
  BOYISD: 'Isolated Danger Buoy',
  BOYSAW: 'Safe Water Buoy',
  BOYSPP: 'Special Purpose Buoy',
  BCNLAT: 'Lateral Beacon',
  BCNCAR: 'Cardinal Beacon',
  BCNISD: 'Isolated Danger Beacon',
  BCNSAW: 'Safe Water Beacon',
  BCNSPP: 'Special Purpose Beacon',
  LNDMRK: 'Landmark',
  SLCONS: 'Shoreline Construction',
  RESARE: 'Restricted Area',
  ACHARE: 'Anchorage Area',
  CBLSUB: 'Submarine Cable',
  PIPSOL: 'Submarine Pipeline',
  BERTHS: 'Berth',
  MORFAC: 'Mooring Facility',
  DISMAR: 'Distance Mark',
  CURENT: 'Current',
  TOPMAR: 'Top Mark',
  RTPBCN: 'Radar Transponder Beacon',
  RDOSTA: 'Radio Station',
  RADSTA: 'Radar Station',
  FOGSIG: 'Fog Signal',
  PILBOP: 'Pilot Boarding Place',
  CGUSTA: 'Coast Guard Station',
  RSCSTA: 'Rescue Station',
  SISTAT: 'Signal Station',
  SISTAW: 'Signal Station Warning',
  HRBFAC: 'Harbour Facility',
  SMCFAC: 'Small Craft Facility',
  CRANES: 'Crane',
  GATCON: 'Gate',
  BRIDGE: 'Bridge',
  CONVYR: 'Conveyor',
  PIPOHD: 'Overhead Pipeline',
  CBLOHD: 'Overhead Cable',
  OFSPLF: 'Offshore Platform',
  LITFLT: 'Light Float',
  LITVES: 'Light Vessel',
  FSHFAC: 'Fishing Facility'
};

export const S57_CLICKABLE_LAYERS = new Set([
  'LIGHTS',
  'BOYLAT',
  'BOYCAR',
  'BOYISD',
  'BOYSAW',
  'BOYSPP',
  'BCNLAT',
  'BCNCAR',
  'BCNISD',
  'BCNSAW',
  'BCNSPP',
  'TOPMAR',
  'RTPBCN',
  'RDOSTA',
  'RADSTA',
  'FOGSIG',
  'LITFLT',
  'LITVES',
  'OBSTRN',
  'UWTROC',
  'WRECKS',
  'LNDMRK',
  'SLCONS',
  'BRIDGE',
  'OFSPLF',
  'PILBOP',
  'CRANES',
  'GATCON',
  'MORFAC',
  'BERTHS',
  'HRBFAC',
  'SMCFAC',
  'CBLSUB',
  'CBLOHD',
  'PIPSOL',
  'PIPOHD',
  'CGUSTA',
  'RSCSTA',
  'SISTAT',
  'SISTAW',
  'DISMAR',
  'CURENT',
  'FSHFAC',
  'CONVYR',
  'RESARE',
  'ACHARE'
]);
