import { Type, isDevMode, provideZonelessChangeDetection } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import {
  provideHttpClient,
  withInterceptorsFromDi
} from '@angular/common/http';
import { provideServiceWorker } from '@angular/service-worker';
import { AppComponent } from './app/app.component';

// Sentry runs only in production AND only when the host injected a DSN
// (the SignalK server plugin can inject __FB_SENTRY_DSN__ at serve time;
// kiosk-mode and dev-mode skip the load). Lazy-import keeps the ~32 KB
// Sentry browser SDK out of the eager bundle for users without a DSN.
const SENTRY_DSN = (window as { __FB_SENTRY_DSN__?: string }).__FB_SENTRY_DSN__;
if (SENTRY_DSN && !isDevMode()) {
  void import('@sentry/browser').then((Sentry) => {
    Sentry.init({
      dsn: SENTRY_DSN,
      integrations: [Sentry.browserTracingIntegration()],
      tracesSampleRate: 0.1,
      environment: 'production'
    });
  });
}

/**
 * Lazy /design-system route.
 *
 * The Angular router is not currently wired into this app; AppComponent is
 * bootstrapped directly. Rather than introduce the router runtime in this
 * batch (and bundle its overhead into every freeboard load), we gate the
 * design-system showcase behind a path check and dynamic import.
 *
 * Why this is "lazy" enough:
 *  - `import('./app/design-system/design-system-showcase.component')` is a
 *    code-split point in esbuild/Angular CLI builds, so the design-system
 *    chunk is its own JS file that never ships to the AppComponent route.
 *  - The chunk is only fetched when the URL path contains `/design-system`.
 *
 * Path matching: substring match on pathname so any base href (signalk-server
 * mounts freeboard-sk under `/@signalk/freeboard-sk/`, dev server at `/`)
 * resolves the same way.
 */
function isDesignSystemRoute(): boolean {
  return window.location.pathname.includes('/design-system');
}

const providers = [
  provideZonelessChangeDetection(),
  provideHttpClient(withInterceptorsFromDi()),
  // PWA: ngsw-worker.js is generated by `ng build` when serviceWorker is
  // enabled in angular.json. Falls back to no-op when SW is not registered
  // (dev mode, missing file).
  provideServiceWorker('ngsw-worker.js', {
    enabled: !isDevMode(),
    registrationStrategy: 'registerWhenStable:30000'
  })
];

if (isDesignSystemRoute()) {
  import('./app/design-system/design-system-showcase.component')
    .then((m) =>
      bootstrapApplication(m.DesignSystemShowcaseComponent as Type<unknown>, {
        providers
      })
    )
    .catch((e) => console.error(e));
} else {
  bootstrapApplication(AppComponent, { providers }).catch((e) =>
    console.error(e)
  );
}
