import { Type, isDevMode, provideZonelessChangeDetection } from '@angular/core';
import { bootstrapApplication } from '@angular/platform-browser';
import {
  provideHttpClient,
  withInterceptorsFromDi
} from '@angular/common/http';
import { provideServiceWorker } from '@angular/service-worker';
import { AppComponent } from './app/app.component';

// Default 2D canvas contexts to willReadFrequently: true when the
// caller did not say otherwise. OpenLayers' hit-detection path
// (forEachFeatureAtCoordinate) creates a shared scratch canvas via
// `getSharedCanvasContext2D` without passing the flag, then calls
// getImageData on every map click. Chromium emits a "Multiple readback
// operations" perf warning to the console on every click in
// chunk-OFNP4N2P.js. Setting the flag at the prototype level switches
// the affected contexts to the software-rendered, readback-friendly
// path. App canvases that explicitly want GPU compositing (none today)
// can still opt out by passing `willReadFrequently: false`.
(() => {
  const proto = HTMLCanvasElement.prototype;
  const original = proto.getContext as (
    this: HTMLCanvasElement,
    type: string,
    options?: unknown
  ) => RenderingContext | null;
  proto.getContext = function (
    this: HTMLCanvasElement,
    type: string,
    options?: CanvasRenderingContext2DSettings | unknown
  ) {
    if (type === '2d') {
      const settings = (options ?? {}) as CanvasRenderingContext2DSettings;
      if (settings.willReadFrequently === undefined) {
        return original.call(this, type, {
          ...settings,
          willReadFrequently: true
        });
      }
    }
    return original.call(this, type, options);
  } as typeof proto.getContext;
})();

// Sentry runs only in production AND only when the host injected a DSN
// (the SignalK server plugin can inject __FB_SENTRY_DSN__ at serve time;
// kiosk-mode and dev-mode skip the load). Lazy-import keeps the ~32 KB
// Sentry browser SDK out of the eager bundle for users without a DSN.
// __FB_RELEASE__ ties runtime errors to the CI source-map upload (the
// tag-build workflow uploads under release == github.ref_name); leaving
// it unset is harmless but stack traces stay minified.
const sentryGlobals = window as {
  __FB_SENTRY_DSN__?: string;
  __FB_RELEASE__?: string;
};
const SENTRY_DSN = sentryGlobals.__FB_SENTRY_DSN__;
const SENTRY_RELEASE = sentryGlobals.__FB_RELEASE__;
if (SENTRY_DSN && !isDevMode()) {
  void import('@sentry/browser').then((Sentry) => {
    Sentry.init({
      dsn: SENTRY_DSN,
      ...(SENTRY_RELEASE ? { release: SENTRY_RELEASE } : {}),
      integrations: [Sentry.browserTracingIntegration()],
      tracesSampleRate: 0.1,
      environment: 'production'
    });
  });
}

// AppComponent is bootstrapped directly: @angular/router is not wired in,
// so the design-system showcase loads via a path check plus dynamic import.
// The dynamic import is a code-split point, so the showcase chunk never
// ships in the AppComponent path. Substring match on pathname keeps it
// working under any base href (signalk-server mounts at
// /signalk-open-binnacle/, dev server at /).
function isDesignSystemRoute(): boolean {
  return window.location.pathname.includes('/design-system');
}

const providers = [
  provideZonelessChangeDetection(),
  provideHttpClient(withInterceptorsFromDi()),
  // PWA: ngsw-worker.js is generated by `ng build` when serviceWorker is
  // enabled in angular.json. Falls back to no-op when SW is not registered
  // (dev mode, missing file).
  provideServiceWorker('ngsw-worker.js', {
    enabled: !isDevMode(),
    registrationStrategy: 'registerWhenStable:30000'
  })
];

if (isDesignSystemRoute()) {
  import('./app/design-system/design-system-showcase.component')
    .then((m) =>
      bootstrapApplication(m.DesignSystemShowcaseComponent as Type<unknown>, {
        providers
      })
    )
    .catch((e) => console.error(e));
} else {
  bootstrapApplication(AppComponent, { providers }).catch((e) =>
    console.error(e)
  );
}
